### ISSUE TITLE
Skeleton code including object tracking and drone control

### ISSUE THREAD

**Issue by jmariscal-harana** [jmariscal-harana/drone-follows-drone#1]
I want to have a first iteration with placeholders and clear interfaces:
- [x] Docker setup including Python + OCV
- [x] Skeleton code for SDK + Object Tracking + Control

I have overdone it and have now moved on to the first implementation of each component:
- [x] SDK including UDP connections, state and video stream
- [x] First tracking algorithm - in fact, multiple traditional algorithms!
- [ ] First control algorithm
